apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-backend
  labels:
    app: api-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-backend
  template:
    metadata:
      labels:
        app: api-backend
    spec:
      containers:
      - name: api-backend
        image: andyy5/my-backend-api
        ports:
        - name: api-backend
          containerPort:  887
---
apiVersion: v1
kind: Service
metadata:
  name: api-backend
  labels:
    app: api-backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 887
  selector:
    app: api-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spa-frontend
  labels:
    app: spa-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spa-frontend
  template:
    metadata:
      labels:
        app: spa-frontend
    spec:
      containers:
      - name: spa-frontend
        image: nginx
---
kind: Service
apiVersion: v1
metadata:
  name:  spa-frontend
spec:
  selector:
    app:  spa-frontend
  type:  ClusterIP
  ports:
  - name:  spa-frontend
    port:  80
    targetPort:  80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-cluster
  namespace: default
  labels:
    app: postgres-cluster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres-cluster
  template:
    metadata:
      name: postgres-cluster
      labels:
        app: postgres-cluster
    spec:
      containers:
        - name: postgres-cluster
          image: postgres
          ports:
          - name: postgres-port
            containerPort: 5432
---
kind: Service
apiVersion: v1
metadata:
  name:  postgres-cluster
spec:
  selector:
    app:  postgres-cluster
  type:  ClusterIP
  ports:
  - name:  postgres-service
    port:  80
    targetPort:  5432
